---
stages:
- name: Build Preparation Stage
  inputs:
  - type: git
    branch: master
    service: ${REPO}
  properties:
  - name: VI_INSTANCE_NAME
    value: NodeVSIforDevOps
    type: text
  - name: PUBLIC_KEY
    value: "${PUBLIC_KEY}"
    type: secure
  - name: PRIVATE_KEY
    value: "${PRIVATE_KEY}"
    type: secure
  - name: TF_VAR_ibm_sl_username
    value: "${TF_VAR_ibm_sl_username}"
    type: text
  - name: TF_VAR_ibm_sl_api_key
    value: "${TF_VAR_ibm_sl_api_key}"
    type: secure
  - name: TF_VAR_ibm_cloud_api_key
    value: "${API_KEY}"
    type: secure
  - name: GIT_USER
    value: "${GITLAB_USERNAME}"
    type: text
  - name: GIT_PASSWORD
    value: "${GITLAB_ACCESS_TOKEN}"
    type: secure
  jobs:
  - name: Validate
    type: builder
    artifact_dir: ''
    build_type: shell
    script: |
      #!/bin/bash
      set -eo pipefail
      bash terraform/scripts/validate.sh